### ISSUE TITLE
Ruby/Rails - colors too similar? (both luna and luna-term)

### ISSUE THREAD

**Issue by Trevoke** [notpratheek/vim-luna#2]
Check this out. This may be intentional, but I find it hard to distinguish quickly between 'File' and 'join' or, really, anything on those lines.
1. Luna
   ![screen shot 2013-07-01 at 11 17 53 pm](https://f.cloud.github.com/assets/67913/734391/08b71656-e2c6-11e2-9f0a-9f00639dc124.png)
2. Luna-term
   ![screen shot 2013-07-01 at 11 18 44 pm](https://f.cloud.github.com/assets/67913/734397/1faa3c8a-e2c6-11e2-8981-9e5d36ff7d83.png)

**Comment by notpratheek** [comment]
@Trevoke

rubyMethodBlock was highlighted with the same colour of Type, so I changed it to " Special's "  colour, and here's how it looks,

#### Gvim

![ruby_special](https://f.cloud.github.com/assets/1803997/757833/d7fd3ce6-e6f5-11e2-8216-85a28e2f921e.png)

#### Console Vim

![ruby_term_special](https://f.cloud.github.com/assets/1803997/757840/20fced8c-e6f7-11e2-9093-5c162881ab54.png)

this is with out highlighting the rubyMethodBlock

![ruby_normal](https://f.cloud.github.com/assets/1803997/757834/f51d4276-e6f5-11e2-9982-705429ef02cd.png)

Tell me, which is them is better :)

P.S.: I installed tpope's vim-rails, as i found that i had better ruby syntax highlighting !

**Comment by Trevoke** [comment]
I think the first one may be closest to the result you are trying to achieve.

**Comment by notpratheek** [comment]
@Trevoke 

First off, I'm **really sorry** for not responding to this for a long time. I had forgotten about this completely ! Sorry ! :sweat_smile: 

Anyway, I update the scheme, and it now has a hint of orange, instead of pink / baby pink Check it out ! 

#### Gvim

![check](https://f.cloud.github.com/assets/1803997/900033/932d8f3e-fb55-11e2-8537-81f566753306.png)

---

#### Console Vim

![check_term](https://f.cloud.github.com/assets/1803997/900037/a76b1bd8-fb55-11e2-9b65-ae7f22ef6bc8.png)

## 

Tell me what do you think (As I'm not really good with Ruby, If your comfortable with these colors, I'll push them upstream) !  :smile:

**Comment by notpratheek** [comment]
@Trevoke 

I pushed the changes to `devel` branch, so you might wanna change context (`$ git checkout devel`) after you clone down the repo into your `~/.vim` !

**Comment by Trevoke** [comment]
Hey @Pychimp, no worries! To be truthful, I am not sure that luna is something I want to use (I still like Jellybeans best), but I really like that new change!

I don't know if we can do something about line 44 in your screenshot, where all the words are the same color?

**Comment by notpratheek** [comment]
@Trevoke 

Do you have any **_other**_ ruby syntax support files. I've tried [tpope/vim-rails](https://github.com/tpope/vim-rails) and [vim-ruby/vim-ruby](https://github.com/vim-ruby/vim-ruby), and both make no difference to the line 44 (as seen in the screenshot) ! :confused: 

Suggest me any other Ruby syntax support files, I'll try them out ! 

P.S. `devel` branch is merged into the `master` branch, No need to make a context switch  (`$ git checkout devel`). You can pull down the laster changes on the `master` branch ! :smile:

**Comment by Trevoke** [comment]
You're right, I'm a nincompoop. That line does not change. With this being
said, I think luna looks great! :)

**Comment by Trevoke** [comment]
I just tried this scheme again. Love it. :)
