### ISSUE TITLE
Low contrast on completion menu

### ISSUE THREAD

**Issue by gcollura** [notpratheek/vim-luna#3]
Could you please set more contrast on the fg_color of text in completion menus?
![As seen here](https://f.cloud.github.com/assets/787586/893715/79921f40-faab-11e2-8161-cb4941adfa23.png)

Thanks for the support and for this excellent colorscheme!

Giulio

**Comment by notpratheek** [comment]
@random-cpp 

Check it i made it lighter ! :smile: 

![completetion](https://f.cloud.github.com/assets/1803997/900341/d1853b74-fb5f-11e2-82a4-ceb5dc8e6212.png)

If these colors are comfortable, I think they should be a **_wee**_ bit darker ! 
Tell me If I should make any more changes to it ! :smile:

**Comment by notpratheek** [comment]
@random-cpp  

I pushed the changes to `devel` branch, so you might wanna change context (`$ git checkout devel`) after you clone down the repo !

**Comment by gcollura** [comment]
Thanks a lot! Could you please also improve the colouring of SignColumn? Thanks again!

**Comment by notpratheek** [comment]
@random-cpp  

Check this: 

![singfixed](https://f.cloud.github.com/assets/1803997/905343/6e4e930e-fc16-11e2-975f-d8d50e3260b9.png) 

I used the [airblade/vim-gitgutter](https://github.com/airblade/vim-gitgutter) to see the `SignColumn`

Again, these are in the `devel` branch, so you might wanna `$ git checkout devel` after you pull down the latest changes

If these are fine, I'll merge them into the master branch ! :smile:

**Comment by gcollura** [comment]
Yes perfect, thank you so much!
